userConsumptionMode: Analytical, Operational  # Modo de consumo pensado para el conjunto de datos
version: 1.0.0  # Version actual del contrato de datos
status: current  # Estado actual 
description: Bucket containing trusted dataset.  # Dueño de los datos estipulados en este contrato. 
tenant: Secretaria de Infraestructura Fisica (SIF)
sourcePlatform: googleCloudPlatform  # Plataforma donde se almacenaran los datos
sourceSystem: googleCloudStorage  # Sistema donde se almacenaran los datos
datasetName: sif-med-lakehouse-trusted-data-dev  # Nombre del dataset en BigQuery
datasetUrl: gs://sif-med-lakehouse-trusted-data-dev/
kind: DataContract  # Tipo de documento
apiVersion: 2.3.0  # Version del Open Data Contract Standard (ODS) usada
dataset:
  - table: sif-med-lakehouse-trusted-data-dev/MOBILE_APP/  # Nombre de la tabla que contiene los datos listados a continuacion
    url: gs://sif-med-lakehouse-trusted-data-dev/MOBILE_APP/
    description: null
    tags: null
    dataGranularity: Aggregation on columns datetime, vib_x, vib_y, vib_z, bridge_name, bridge_coordinates, freq_vib_x, freq_vib_y, freq_vib_z
    columns:
      - column: datetime  # Nombre de una de las columnas que debe de contener la tabla MobileApp
        isPrimary: false  # Si la columna es llave primaria o no
        businessName: concrete measurement date in DD-MM-AA-HH:MM:SS format
        logicalType: Datetime  # Tipo de dato de la columna
        physicalType: Datetime
        isNullable: false  # Si se pueden o no encontrar nulos en la columna
        description: The concrete date and time when the measurement of the vibrations of the X, Y, and Z axes took place
        transformSourceTables:
          - table: sif-med-raw-data/MOBILE_APP  # Tabla fuente de donde se transforman los datos
            url: gs://sif-med-lakehouse-raw-data-dev/sif-med-raw-data/MOBILE_APP/*  # Ruta dentro de GCS a la tabla fuente
        transformLogic: SELECT raw_data.datetime from sif-med-raw-data/MOBILE_APP as raw_data  # No se hace ninguna transformacion solo se hace un SELECT * de la columna
        transformDescription: Insert all values from the datetime column of the sif-med-raw-data/MOBILE_APP table into the datetime column of the sif-med-lakehouse-trusted-data-dev/MOBILE_APP/ table.
        sampleValues:
          - 08-04-2024 9:21:32
          - 06-03-2024 12:31:20
      - column: vib_x
        isPrimary: false
        businessName: concrete measurement of the vibration of the X axis
        logicalType: Float
        physicalType: Float
        isNullable: false
        description: The concrete measurement of the vibrations of the X axis that took place
        transformSourceTables:
          - table: sif-med-raw-data/MOBILE_APP
            url: gs://sif-med-lakehouse-raw-data-dev/sif-med-raw-data/MOBILE_APP/*
        transformLogic: SELECT raw_data.vib_x from sif-med-raw-data/MOBILE_APP as raw_data
        transformDescription: Insert all values from the vib_x column of the sif-med-raw-data/MOBILE_APP table into the vib_x column of the sif-med-lakehouse-trusted-data-dev/MOBILE_APP/ table.
        sampleValues:
          - 0.00079999997979030013
          - 0.010400000028312206
      - column: vib_y
        isPrimary: false
        businessName: concrete measurement of the vibration of the Y axis
        logicalType: Float
        physicalType: Float
        isNullable: false
        description: The concrete measurement of the vibrations of the Y axis that took place
        transformSourceTables:
          - table: sif-med-raw-data/MOBILE_APP
            url: gs://sif-med-lakehouse-raw-data-dev/sif-med-raw-data/MOBILE_APP/*
        transformLogic: SELECT raw_data.vib_y from sif-med-raw-data/MOBILE_APP as raw_data
        transformDescription: Insert all values from the vib_y column of the sif-med-raw-data/MOBILE_APP table into the vib_y column of the sif-med-lakehouse-trusted-data-dev/MOBILE_APP/ table.
        sampleValues:
          - -0.018799999728798866
          - -0.02070000022649765
      - column: vib_z
        isPrimary: false
        businessName: concrete measurement of the vibration of the Z axis
        logicalType: Float
        physicalType: Float
        isNullable: false
        description: The concrete measurement of the vibrations of the Z axis that took place
        transformSourceTables:
          - table: sif-med-raw-data/MOBILE_APP
            url: gs://sif-med-lakehouse-raw-data-dev/sif-med-raw-data/MOBILE_APP/*
        transformLogic: SELECT raw_data.vib_z from sif-med-raw-data/MOBILE_APP as raw_data
        transformDescription: Insert all values from the vib_z column of the sif-med-raw-data/MOBILE_APP table into the vib_z column of the sif-med-lakehouse-trusted-data-dev/MOBILE_APP/ table.
        sampleValues:
          - -0.018799999728798866
          - -0.02070000022649765
      - column: bridge_name
        isPrimary: false
        businessName: the name of the bridge in which the measurement took place
        logicalType: String
        physicalType: String
        isNullable: false
        description: The name of the bridge in which the measurement took place
        transformSourceTables:
          - table: sif-med-raw-data/MOBILE_APP
            url: gs://sif-med-lakehouse-raw-data-dev/sif-med-raw-data/MOBILE_APP/*
        transformLogic: SELECT raw_data.bridge_name from sif-med-raw-data/MOBILE_APP as raw_data
        transformDescription: Insert all values from the bridge_name column of the sif-med-raw-data/MOBILE_APP table into the bridge_name column of the sif-med-lakehouse-trusted-data-dev/MOBILE_APP/ table.
        sampleValues:
          - Puente Gilberto Echeverri Mejía
          - Puente de La Calle 10
      - column: bridge_coordinates
        isPrimary: false
        businessName: the coordinates of the bridge in which the measurement took place
        logicalType: List[Float, Float]
        physicalType: List[Float, Float]
        isNullable: false
        description: The coordinates [longitude, latitude] of the bridge in which the measurement took place
        transformSourceTables:
          - table: sif-med-raw-data/MOBILE_APP
            url: gs://sif-med-lakehouse-raw-data-dev/sif-med-raw-data/MOBILE_APP/*
        transformLogic: SELECT raw_data.bridge_coordinates from sif-med-raw-data/MOBILE_APP as raw_data
        transformDescription: Insert all values from the bridge_coordinates column of the sif-med-raw-data/MOBILE_APP table into the bridge_coordinates column of the sif-med-lakehouse-trusted-data-dev/MOBILE_APP/ table.
        sampleValues:
          - [37.8961199, -4.7830962]
          - [37.3629504, -5.97893023224876]
      - column: freq_vib_x
        isPrimary: false
        businessName: frequencies for the vibrations measured in the X axis
        logicalType: float
        physicalType: float
        isNullable: false
        description: The frequencies obtained when applying the inverse fourier transformation to the vibrations measured in the X axis
        transformSourceTables:
          - table: sif-med-raw-data/MOBILE_APP
            url: gs://sif-med-lakehouse-raw-data-dev/sif-med-raw-data/MOBILE_APP/*
        transformLogic: numpy.ifft(numpy.array(sif-med-raw-data/MOBILE_APP.select("vib_x"))).real  # Todos los valores de la columna vib_x se pasan a un vector; se computa la transformada inversa de fourier para cada uno de los terminos del vector, donde cada uno de los terminos del vector representa una fila.
        transformDescription: Compute the inverse fourier transformation with the values of the entire vib_x column and subtract the real part of the solution. Assign each value to a row.
        sampleValues:
          - 0.00020973576465621591
          - -0.00071145640686154366
      - column: freq_vib_y
        isPrimary: false
        businessName: frequencies for the vibrations measured in the Y axis
        logicalType: float
        physicalType: float
        isNullable: false
        description: The frequencies obtained when applying the inverse fourier transformation to the vibrations measured in the Y axis
        transformSourceTables:
          - table: sif-med-raw-data/MOBILE_APP
            url: gs://sif-med-lakehouse-raw-data-dev/sif-med-raw-data/MOBILE_APP/*
        transformLogic: numpy.ifft(numpy.array(sif-med-raw-data/MOBILE_APP.select("vib_y"))).real
        transformDescription: Compute the inverse fourier transformation with the values of the entire vib_y column and subtract the real part of the solution. Assign each value to a row.
        sampleValues:
          - -0.0089790131896734238
          - 0.0010807259241119027
      - column: freq_vib_z
        isPrimary: false
        businessName: frequencies for the vibrations measured in the Z axis
        logicalType: float
        physicalType: float
        isNullable: false
        description: The frequencies obtained when applying the inverse fourier transformation to the vibrations measured in the Z axis
        transformSourceTables:
          - table: sif-med-raw-data/MOBILE_APP
            url: gs://sif-med-lakehouse-raw-data-dev/sif-med-raw-data/MOBILE_APP/*
        transformLogic: numpy.ifft(numpy.array(sif-med-raw-data/MOBILE_APP.select("vib_z"))).real
        transformDescription: Compute the inverse fourier transformation with the values of the entire vib_z column and subtract the real part of the solution. Assign each value to a row.
        sampleValues:
          - 0.00057652068790048361
          - 0.0010317020351067185