version: "3.9"

services:
  jupyter-spark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter-spark
    networks:
      - spark-network
    ports:
      - "8888:8888" # Jupyter notebooks UI
      - "4040:4040" # Spark UI
    volumes:
      - ./src:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token='' # Remove the Token auth requirement
  
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"
    networks:
      - spark-network
  
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
      - spark-network
    depends_on:
      - zookeeper

networks:
  spark-network:
    driver: bridge
